title: No scientist is an island
description: Working smarter to share data derivatives
theme: 
  name: just-the-docs
  custom_css:
    - "assets/css/custom.css"

url: https://no-scientist-is-an-island.github.io/no-scientist-is-an-island

# aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
